version: '2'
services:

  java8:
    build: ./java8/
    container_name: java8

  zk1:
    build: ./zookeeper/
    container_name: zk1
    environment:
      - ZOOKEEPER_ID=1
    depends_on:
      - java8
    network_mode: "host"

  zk2:
    build: ./zookeeper/
    container_name: zk2
    environment:
      - ZOOKEEPER_ID=2
    depends_on:
      - java8
    network_mode: "host"

  zk3:
    build: ./zookeeper/
    container_name: zk3
    environment:
      - ZOOKEEPER_ID=3
    depends_on:
      - java8
    network_mode: "host"

  kafka1:
    build: ./kafka/
    container_name: kafka1
    depends_on:
      - zk1
      - zk2
      - zk3
    environment:
      - KAFKA_ID=1
    network_mode: "host"

  kafka2:
    build: ./kafka/
    container_name: kafka2
    depends_on:
      - zk1
      - zk2
      - zk3
    environment:
      - KAFKA_ID=2
    network_mode: "host"

  kafka3:
    build: ./kafka/
    container_name: kafka3
    depends_on:
      - zk1
      - zk2
      - zk3
    environment:
      - KAFKA_ID=3
    network_mode: "host"

  kafka4:
    build: ./kafka/
    container_name: kafka4
    depends_on:
      - zk1
      - zk2
      - zk3
    environment:
      - KAFKA_ID=4
    network_mode: "host"

  kafka5:
    build: ./kafka/
    container_name: kafka5
    depends_on:
      - zk1
      - zk2
      - zk3
    environment:
      - KAFKA_ID=5
    network_mode: "host"

  kafka-manager:
    build: ./kafka-manager/
    container_name: kafka-manager
    depends_on:
      - zk1
      - zk2
      - zk3
      - kafka1
      - kafka2
      - kafka3
      - kafka4
      - kafka5
    environment:
      - ZK_HOSTS=localhost:2181,localhost:2182,localhost:2183
    network_mode: "host"

  redis:
    build: ./redis/
    network_mode: "host"

  mysql:
    build: ./mysql/
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=changeit
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=dbunit
      - MYSQL_PASSWORD=dbunit
    network_mode: "host"

    # volumes:
    #   - ./docker-data/mysql/:/var/lib/mysql
